version: "3"

services:
  debian-python:
      container_name: debian-python
      build: .
      env_file:
        - ./.env
      stop_signal: SIGINT 
      ports:
      - '8000:8000'
      volumes:
        - ${PWD}/data:/data