version: "3"

services:
  python:
      container_name: python
      build: .
      env_file:
        - ./.env
      stop_signal: SIGINT 
      ports:
      - '8000:8000'
      volumes:
        - ${PWD}/data:/data